### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [wulfeku3/project3#1]
:+1: Looks good. The only new comment I might have is that for inline CSS, I think it looks nicer to pad a space around braces. So for example, I prefer:

``` css
body { background: orange; }
```

over:

``` css
body {background: orange;}
```
